version: "3.9"

services:
  django:
    container_name: django
    build:
      context: .
    command: uvicorn push_notification.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env_vars_django.txt

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery --app=push_notification worker -l INFO -B
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./env_vars_django.txt
